### ISSUE TITLE
Can not update "awaitTimeout" option after creating socket

### ISSUE THREAD

**Issue by hopbkpro92** [stas-ut21/ws-await#18]
@stas-ut21 
Currently, I see that, "**awaitTimeout**" option (timeout for waiting response message) only is set when create new socket (**new WebSocket(address[, protocols][, options]**) . Is is right ?
If not, how to modify this option after creating socket (similar modify "defaults.timeout" after creating Axios instance)

Many thanks

**Comment by stas-ut21** [comment]
@hopbkpro92 Hello

At the moment it is only possible as follows: 

```js
const ws = new WebSocketAwait('ws://localhost:6060', options);

ws._options.awaitTimeout = 3000;
```

**Comment by stas-ut21** [comment]
i can implement this in future versions

**Comment by hopbkpro92** [comment]
@stas-ut21 Hello

> const ws = new WebSocketAwait('ws://localhost:6060', options);
   ws._options.awaitTimeout = 3000;

It means that, at the moment, I also can update "**awaitTimeout**" after "**sendAwait**" using "**ws._options.awaitTimeout**".

Is it right ?
Many thanks

**Comment by stas-ut21** [comment]
@hopbkpro92 
Yes, this is the only way

**Comment by stas-ut21** [comment]
@hopbkpro92 Hello
I am update module and add method `setAwaitTimeout` for update await timeout option
Check in version `4.1.0`
Thanks

**Comment by stas-ut21** [comment]
Closed
