### ISSUE TITLE
Lack of Typescript definition

### ISSUE THREAD

**Issue by hopbkpro92** [stas-ut21/ws-await#19]
@stas-ut21 Hello
I see that, current implementation lack of Typescript definition similar to [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ws/index.d.ts](url)

Is it right ?
I think Typescript definition is necessary.

Many thanks

**Comment by stas-ut21** [comment]
@hopbkpro92 Hello
I agree that this is necessary
Soon to be added

**Comment by stas-ut21** [comment]
@hopbkpro92 Hello
Added in `4.2.3` version

**Comment by remss** [comment]
In package.json the "types" entry is missing to declare the type definitions.
```
{
  ...
  "types": "./index.d.ts",
  ...
}
```
