### ISSUE TITLE
Some message will be ignored when using sendAwait()

### ISSUE THREAD

**Issue by hopbkpro92** [stas-ut21/ws-await#21]
@stas-ut21 Hello

I have a concern point. Could you please help me confirm it.

In current implementation, use sendAwait() to send a request (id = xxx) to server as below:
```
const ws = new WebSocketAwait('ws://localhost:8080');
ws.on('message', message => {
    console.log(message);
});

const waiting = await ws.sendAwait({ // id = xxx
    foo: 'bar'
});
```
I use sendAwait() to send request (id = xxx) to server and wait until server response (id = xxx). If in waiting time for response (id = xxx), server returns a other response (id = yyy), I think this response (id = yyy) will be ignored (does not jump to **ws.on('message')**). Is it right ?

Many thanks.

**Comment by stas-ut21** [comment]
Hello @hopbkpro92 
Yes that's right
This is because the client is waiting for a specific ID that it use to find Promise and call resolve or reject

**Comment by hopbkpro92** [comment]
@stas-ut21, many thanks for your response.
If server returns a other response (without id), this response will be kept (jump to ws.on('message')).
Is it right ?

Many thanks

**Comment by stas-ut21** [comment]
@hopbkpro92 , yes it’s right

**Comment by stas-ut21** [comment]
@hopbkpro92 
do you still have a problem? or is it solved

**Comment by hopbkpro92** [comment]
@stas-ut21 
It was solved.
Thanks you very much
