### ISSUE TITLE
Current version requires older version of ws project

### ISSUE THREAD

**Issue by lynniemagoo** [stas-ut21/ws-await#24]
Can we please get a newer version that has been tested with ws 7.4.1 published to NPM (7.4.1 is the latest as of this posting).

Thanks in advance,
Lynnie

**Comment by stas-ut21** [comment]
@lynniemagoo Hello
Added in version `4.2.0`

**Changelog:**
- Upgrade ws to 7.4.1
- Upgrade mocha to 7.2.0
- Upgrade nyc to 15.1.0
- Update `.travis.yml` for NodeJS 14
- Update package-lock.json
- Upgrade `completeUpgrade` method in `websocket-server.js`

Thanx

**Comment by lynniemagoo** [comment]
Many thanks and Happy Holidays.  Stay Safe.

**Comment by stas-ut21** [comment]
Thank you, and Happy Holidays and health to you and your family
